title: Welcome to my page! =)
email: a.akhunov@yourapi.ru
description: >- # this means to ignore newlines until "baseurl:"
  I have experience in design and development of microservices-based application architecture by using following technologies ->
  Java, Kafka, gRPC, Spring, Docker, Kubernetes. These skills are confirmed by extensive working and developing in a range of prior positions. 
  I have a good experience in developing in ReactJS. This knowledge allows me effectively contribute my skills as Software Professional, 
  possessing competent Technical Skills. I like to read, play on guitar, learn something new, and also teach someone.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  akhunovaa

# # Build settings
# theme: minima
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
